Task_1_1
chronorose/OOP pull request #2
Opened 2024-09-06 13:53 UTC by chronorose

2024-09-07 13:05 UTC, Sharapov-Maksim requested changes
Посмотрел, можете исправлять замечания и оставлять комментарии.
Когда считаете, что замечание исправлено, напишите об этом в ответ на мой комментарий

2024-09-07 13:05 UTC, Sharapov-Maksim commented on Task_1_1/src/main/java/ru/nsu/Heap.java
> + * {@link Heap} class for max-heap
GitHub Actions / checkstyle ругается на отсутствие точки в конце

> 7.2 The summary fragment
> ... the fragment is capitalized and punctuated as if it were a complete sentence.
[link](https://google.github.io/styleguide/javaguide.html#s7.2-summary-fragment)

2024-09-07 13:05 UTC, Sharapov-Maksim commented on Task_1_1/src/main/java/ru/nsu/Heap.java
> +        heapify();
Получается, что вся полезная работа выполняется в конструкторе объекта `Heap`, при этом сам объект в дальнейшем использовать никак особенно нельзя. В целом, для решения задачи сортировки не обязательно создавать новый объект, достаточно прсто `static` функции, принимающей массив и сортирующей его `in place`.
Т. е. в данном случае будет сделать `public static heapify(array)`, и не создавать вспомогательного объекта `Heap` для этих целей.

Если же хочется создать объект `Heap`, то нужно довести его до полноценной структуры данных: скопировать входной массив, сделать getter отсортированного массива. В данной задаче это излишнее усложнение. На объектно-ориентированный подход будут следующие задачи =)

2024-09-07 13:05 UTC, Sharapov-Maksim commented on Task_1_1/src/main/java/ru/nsu/Heap.java
> +    public void siftDown(int start, int limit) {
`siftDown` аналогично может быть статическим и принимать массив в качестве аргумента

2024-09-07 13:05 UTC, Sharapov-Maksim commented on Task_1_1/src/test/java/ru/nsu/HeapSortTest.java
> +class HeapSortTest {
> При сдаче задания преподавателю объясните, как выбранный набор тестов обеспечивает корректность вашего алгоритма.

Нужно либо объяснить, почему такого скромного набора тестов достаточно, либо добавить тестов на краевые случаи (например: массив пустой, из одного элемента, ...) и разные входные данные (одинаковые числа, отрицательные/положительные значения, ...)

2024-09-07 13:05 UTC, Sharapov-Maksim commented on Task_1_1/src/test/java/ru/nsu/HeapTest.java
> +        Heap heap = new Heap(arr);
К слову о избыточности объекта класса `Heap`, здесь переменная `heap` даже не используется, а массив всё равно получилось отсортировать.
Этот код эквивалентен
```
int[] arr = new int[]{4, 7, 8, 10, 3, 7, 10};
new Heap(arr);
assertTrue(testIfMaxHeap(arr, 0));
```
на месте `new Heap(...);` вполне мог быть вызов статического метода, ничего бы не изменилось

2024-09-07 13:05 UTC, Sharapov-Maksim commented on Task_1_1/src/test/java/ru/nsu/UtilTest.java
> +    void testSwap() {
Тесты на вспомогательные методы это хорошо и правильно. Только побольше бы их, на разные краевые случаи

2024-09-07 13:38 UTC, chronorose commented on Task_1_1/src/main/java/ru/nsu/Heap.java
> +    public void siftDown(int start, int limit) {
Здравствуйте, меня интересует что идиоматичнее в Java при написании статического метода принимающего массив(ну и в целом что-либо что может быть null'ем). Проверять инварианты на входе в функцию или давать юзеру самому за этим следить

2024-09-07 14:07 UTC, Sharapov-Maksim commented on Task_1_1/src/main/java/ru/nsu/Heap.java
> +    public void siftDown(int start, int limit) {
Вообще, в подобных ситуациях можно посмотреть, как такое делается в стандартной библиотеке. Зачастую явных проверок на `null` нет, но в javadoc дописывается `@throws NullPointerException`.

Пример из `java.util.Arrays`
![image](https://github.com/user-attachments/assets/92d5c347-f197-4bd7-8c0d-e447bd313641)

2024-09-07 14:44 UTC, chronorose commented
> Посмотрел, можете исправлять замечания и оставлять комментарии. Когда считаете, что замечание исправлено, напишите об этом в ответ на мой комментарий

Исправил замечания, жду повторного ревью :D

2024-09-08 05:50 UTC, Sharapov-Maksim requested changes

2024-09-08 05:50 UTC, Sharapov-Maksim commented on Task_1_1/src/main/java/ru/nsu/Heap.java
> +     * @throws NullPointerException
`@throws NullPointerException` when ...

checkstyle ругается на отстутствие описания. Следите самостоятельно за checkstyle warnings, и не стесняйтесь исправлять без моего напоминания =)

2024-09-08 06:15 UTC, Sharapov-Maksim requested changes

2024-09-08 06:15 UTC, Sharapov-Maksim commented on Task_1_1/build.sh
> +javac -d ./build/classes/java/main/ru/nsu ./src/main/java/ru/nsu/*.java
А давайте всё таки сделаем функцию `main` и добавим в скрипт запуск приложения через `java`, просто чтобы попрактиковаться. Оно же неспроста в условиях задания

2024-09-08 06:55 UTC, Sharapov-Maksim commented
На покрытие можно не смотреть, оно как-то странно считается. А вот скрипт не работает, возможно формат директории для `javac` содержит ошибку...

2024-09-08 09:51 UTC, chronorose commented on Task_1_1/build.sh
> +javac -d ./build/classes/java/main/ru/nsu ./src/main/java/ru/nsu/*.java
исправлено

2024-09-08 09:51 UTC, chronorose commented on Task_1_1/src/main/java/ru/nsu/Heap.java
> +     * @throws NullPointerException
исправлено

2024-09-09 10:21 UTC, chronorose commented
> На покрытие можно не смотреть, оно как-то странно считается. А вот скрипт не работает, возможно формат директории для `javac` содержит ошибку...

Исправил скрипт :)

2024-09-09 10:52 UTC, Sharapov-Maksim approved these changes
Замечания исправлены

2024-09-09 10:52 UTC, merged