Task_1_1_2
chronorose/OOP pull request #3
Opened 2024-09-10 16:19 UTC by chronorose

2024-09-14 07:31 UTC, Sharapov-Maksim requested changes
Мягкий дедлайн зачтён. Доделывайте реализацию и тесты, приводите код в порядок

2024-09-14 07:31 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/Deck.java
> +    private int getUnusedCard() {
Рекурсивная реализация, где мы случайно тыкаемся в произвольные карты пока нам не попадётся нужная - неудачное решение. Мало того, что это не эффективно, так ещё и возможно уйти в бесконечную рекурсию, если рандом будет неудачный.

Можно удалять из массива уже вытащенные карты или заранее сделать random shaffle массива

2024-09-14 07:31 UTC, Sharapov-Maksim commented on Task_1_1_2/src/main/java/ru/nsu/Dealer.java
> +class Dealer extends Player {
Ого, уже наследование используете, неплохо)
Расскажите тогда, что такое наследование и почему вы здесь решили применить этот механизм?

2024-09-23 16:00 UTC, chronorose commented on Task_1_1_2/src/main/java/ru/nsu/Deck.java
> +    private int getUnusedCard() {
исправлено

2024-09-23 16:03 UTC, chronorose commented on Task_1_1_2/src/main/java/ru/nsu/Dealer.java
> +class Dealer extends Player {
концепция в которой один тип данных "наследует" (определяет такие же) данные и методы от некоторого другого типа данных. использовал здесь т.к. дилер в моей логике практически полностью дублирует функционал игрока за исключением 1-2 методов.

2024-09-23 16:05 UTC, chronorose commented
> File 	Coverage [66.78%] 	❌
> [Card.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fcards%2FCard.java) 	100% 	🍏
> [Kind.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fcards%2FKind.java) 	100% 	🍏
> [CardValue.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fcards%2FCardValue.java) 	100% 	🍏
> [GameScore.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fgame%2FGameScore.java) 	100% 	🍏
> [GameState.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fgame%2FGameState.java) 	100% 	🍏
> [Turn.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fgame%2FTurn.java) 	100% 	🍏
> [Result.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fgame%2FResult.java) 	100% 	🍏
> [Player.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fplayers%2FPlayer.java) 	100% 	🍏
> [Dealer.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fplayers%2FDealer.java) 	100% 	🍏
> [Deck.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fcards%2FDeck.java) 	95.24% 	🍏
> [PlayerInput.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fgame%2FPlayerInput.java) 	91.89% 	🍏
> [GameIO.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fgame%2FGameIO.java) 	65.55% 	❌
> [Main.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2FMain.java) 	0% 	❌
> [Game.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fgame%2FGame.java) 	0% 	❌
> [HandState.java](https://github.com/chronorose/OOP/blob/2fa10984a3348f4c76dc268e6157242093d1a8a7/Task_1_1_2%2Fsrc%2Fmain%2Fjava%2Fru%2Fnsu%2Fgame%2FHandState.java) 	0% 	❌
> Total Project Coverage 	66.78% 	❌

честно сказать слабо понимаю как ещё GameIO затестить, ну и то что оно хочет чтобы я HandState затестил как-то это слегка фейспалм

2024-09-24 05:15 UTC, Sharapov-Maksim requested changes
Замечания выданы на семинаре

2024-09-24 11:56 UTC, chronorose commented
> Замечания выданы на семинаре

Здравствуйте, исправлены замечания выданные на семинаре(исправил хэндлинг ошибок при вводе пользователя, добавил тесты для Game.java)

2024-09-24 14:57 UTC, Sharapov-Maksim approved these changes
Замечания исправлены, задание зачтено, PR можно мёржить

2024-09-24 15:00 UTC, merged