Task_1_4_1
chronorose/OOP pull request #6
Opened 2024-11-25 14:38 UTC by chronorose

2024-11-25 18:01 UTC, Sharapov-Maksim requested changes
\+ javadoc

2024-11-25 18:01 UTC, Sharapov-Maksim commented on Task_1_4_1/src/main/java/ru/nsu/Subject.java
> +    int grade;
Давайте для оценки сделаем `enum`, у которого будет конструктор с численным значением. Так будет фиксированное множество возможных оценок.

2024-11-25 18:01 UTC, Sharapov-Maksim commented on Task_1_4_1/src/main/java/ru/nsu/GradeBook.java
> +                .reduce(true, (x, y) -> x && y);
Можно заменить на 
```
.allMatch(x -> x.grade >= 4)
```

2024-11-25 18:01 UTC, Sharapov-Maksim commented on Task_1_4_1/src/main/java/ru/nsu/GradeBook.java
> +                .reduce(true, (x, y) -> x && y);
И в `honorsDiploma()` в такие пары map-reduce есть

2024-11-25 18:07 UTC, Sharapov-Maksim requested changes

2024-11-25 18:07 UTC, Sharapov-Maksim commented on Task_1_4_1/src/main/java/ru/nsu/GradeBook.java
> +        return gradeSum / count;
`count` кстати может быть нулём, поправьте и добавьте тест

2024-11-26 06:56 UTC, chronorose commented on Task_1_4_1/src/main/java/ru/nsu/Subject.java
> +    int grade;
Исправил

2024-11-26 06:56 UTC, chronorose commented on Task_1_4_1/src/main/java/ru/nsu/GradeBook.java
> +                .reduce(true, (x, y) -> x && y);
Исправил

2024-11-26 06:56 UTC, chronorose commented on Task_1_4_1/src/main/java/ru/nsu/GradeBook.java
> +        return gradeSum / count;
Исправил

2024-11-26 07:26 UTC, Sharapov-Maksim approved these changes
Задание зачтено, PR можно мёржить

2024-12-09 13:13 UTC, merged